"""Lightweight SQLite persistence layer for the adaptive retail management system.

This module provides a local database backend for tracking:

- retail products and stock levels,
- historical demand and sales volume,
- forecast records generated by the adaptive forecasting system,
- inventory recommendations produced by the inventory planning layer.

The implementation intentionally avoids any external service dependency and remains
compatible with the project's existing forecasting and inventory modules.
"""

from __future__ import annotations

import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union


class RetailDatabase:
    """SQLite-backed local data store for retail demand and inventory data."""

    def __init__(self, db_path: Optional[str] = None):
        base_dir = Path(__file__).resolve().parent.parent
        default_path = base_dir / "data" / "retail_management.db"
        self.db_path = Path(db_path) if db_path else default_path

        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._connection: Optional[sqlite3.Connection] = None
        self.initialize_database()

    @property
    def connection(self) -> sqlite3.Connection:
        """Return the active SQLite connection, creating it if needed."""

        if self._connection is None:
            self._connection = sqlite3.connect(str(self.db_path))
            self._connection.row_factory = sqlite3.Row
            self._connection.execute("PRAGMA foreign_keys = ON")
        return self._connection

    def _normalize_timestamp(self, timestamp: Optional[str] = None) -> str:
        """Return an ISO-8601 timestamp string."""

        if timestamp is not None:
            return str(timestamp)
        return datetime.now().isoformat(timespec="seconds")

    def _validate_product_id(self, product_id: Any) -> str:
        """Validate and normalize a product identifier."""

        if product_id is None:
            raise ValueError("product_id is required.")

        product_id = str(product_id).strip()
        if not product_id:
            raise ValueError("product_id cannot be empty.")
        return product_id

    def initialize_database(self) -> None:
        """Create the SQLite database and all required tables if absent."""

        conn = sqlite3.connect(str(self.db_path))
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS products (
                product_id TEXT PRIMARY KEY,
                product_name TEXT NOT NULL,
                category TEXT,
                current_stock REAL NOT NULL DEFAULT 0.0,
                unit_price REAL NOT NULL DEFAULT 0.0,
                reorder_level REAL NOT NULL DEFAULT 0.0,
                supplier TEXT,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS demand_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                product_id TEXT NOT NULL,
                timestamp TEXT NOT NULL,
                demand REAL NOT NULL,
                FOREIGN KEY(product_id) REFERENCES products(product_id) ON DELETE CASCADE
            )
            """
        )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS forecast_records (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                product_id TEXT NOT NULL,
                timestamp TEXT NOT NULL,
                forecasted_demand REAL NOT NULL,
                actual_demand REAL,
                forecast_error REAL,
                drift_score REAL,
                adaptation_status TEXT,
                FOREIGN KEY(product_id) REFERENCES products(product_id) ON DELETE CASCADE
            )
            """
        )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS inventory_recommendations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                product_id TEXT NOT NULL,
                timestamp TEXT NOT NULL,
                safety_stock REAL NOT NULL,
                reorder_point REAL NOT NULL,
                recommended_reorder_quantity REAL NOT NULL,
                stock_out_risk REAL NOT NULL,
                excess_inventory_risk REAL NOT NULL,
                inventory_status TEXT NOT NULL,
                FOREIGN KEY(product_id) REFERENCES products(product_id) ON DELETE CASCADE
            )
            """
        )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS adaptation_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                product_id TEXT,
                timestamp TEXT NOT NULL,
                event_type TEXT NOT NULL,
                details TEXT,
                drift_score REAL,
                adaptation_status TEXT
            )
            """
        )

        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_demand_history_product_time ON demand_history(product_id, timestamp)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_forecast_records_product_time ON forecast_records(product_id, timestamp)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_inventory_recommendations_product_time ON inventory_recommendations(product_id, timestamp)"
        )

        conn.commit()
        conn.close()

    def add_product(
        self,
        product_id: str,
        product_name: str,
        category: Optional[str] = None,
        current_stock: float = 0.0,
        unit_price: float = 0.0,
        reorder_level: float = 0.0,
        supplier: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Insert or replace a product record in the database."""

        normalized_id = self._validate_product_id(product_id)
        if product_name is None or str(product_name).strip() == "":
            raise ValueError("product_name is required.")

        try:
            current_stock_value = float(current_stock)
            unit_price_value = float(unit_price)
            reorder_level_value = float(reorder_level)
        except (TypeError, ValueError) as exc:
            raise ValueError("Stock, unit price, and reorder level must be numeric.") from exc

        record = {
            "product_id": normalized_id,
            "product_name": str(product_name).strip(),
            "category": str(category).strip() if category is not None else None,
            "current_stock": current_stock_value,
            "unit_price": unit_price_value,
            "reorder_level": reorder_level_value,
            "supplier": str(supplier).strip() if supplier is not None else None,
        }

        conn = self.connection
        conn.execute(
            """
            INSERT OR REPLACE INTO products (
                product_id,
                product_name,
                category,
                current_stock,
                unit_price,
                reorder_level,
                supplier
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                record["product_id"],
                record["product_name"],
                record["category"],
                record["current_stock"],
                record["unit_price"],
                record["reorder_level"],
                record["supplier"],
            ),
        )
        conn.commit()
        return self.get_product(normalized_id)

    def get_product(self, product_id: str) -> Optional[Dict[str, Any]]:
        """Return a single product record or None if not found."""

        normalized_id = self._validate_product_id(product_id)
        row = self.connection.execute(
            "SELECT * FROM products WHERE product_id = ?",
            (normalized_id,),
        ).fetchone()

        if row is None:
            return None
        return dict(row)

    def get_all_products(self) -> List[Dict[str, Any]]:
        """Return all products in database order by product_id."""

        rows = self.connection.execute(
            "SELECT * FROM products ORDER BY product_id ASC"
        ).fetchall()
        return [dict(row) for row in rows]

    def update_stock(
        self,
        product_id: str,
        current_stock: Optional[float] = None,
        quantity_delta: Optional[float] = None,
    ) -> Optional[Dict[str, Any]]:
        """Update a product's current stock using either a direct value or a delta."""

        normalized_id = self._validate_product_id(product_id)
        existing = self.get_product(normalized_id)
        if existing is None:
            return None

        if current_stock is None and quantity_delta is None:
            raise ValueError("Either current_stock or quantity_delta must be provided.")

        current_value = float(existing["current_stock"])

        if current_stock is not None:
            new_stock = float(current_stock)
        else:
            new_stock = current_value + float(quantity_delta)

        if new_stock < 0:
            raise ValueError("Stock cannot be negative.")

        self.connection.execute(
            "UPDATE products SET current_stock = ? WHERE product_id = ?",
            (new_stock, normalized_id),
        )
        self.connection.commit()
        return self.get_product(normalized_id)

    def record_demand(
        self,
        product_id: str,
        demand: float,
        timestamp: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Record one demand entry for a product."""

        normalized_id = self._validate_product_id(product_id)
        if self.get_product(normalized_id) is None:
            raise ValueError(f"Product '{normalized_id}' does not exist.")

        try:
            demand_value = float(demand)
        except (TypeError, ValueError) as exc:
            raise ValueError("demand must be numeric.") from exc

        if demand_value < 0:
            raise ValueError("demand cannot be negative.")

        entry_time = self._normalize_timestamp(timestamp)

        cursor = self.connection.execute(
            """
            INSERT INTO demand_history (product_id, timestamp, demand)
            VALUES (?, ?, ?)
            """,
            (normalized_id, entry_time, demand_value),
        )
        self.connection.commit()

        return {
            "id": cursor.lastrowid,
            "product_id": normalized_id,
            "timestamp": entry_time,
            "demand": demand_value,
        }

    def get_demand_history(
        self,
        product_id: str,
        limit: Optional[int] = None,
    ) -> List[Dict[str, Any]]:
        """Return demand history for a product, sorted by newest first or oldest first."""

        normalized_id = self._validate_product_id(product_id)
        if self.get_product(normalized_id) is None:
            return []

        query = (
            "SELECT * FROM demand_history WHERE product_id = ? ORDER BY timestamp DESC"
        )
        params: Tuple[Any, ...] = (normalized_id,)

        if limit is not None:
            query += " LIMIT ?"
            params = (normalized_id, int(limit))

        rows = self.connection.execute(query, params).fetchall()
        return [dict(row) for row in rows]

    def save_forecast(
        self,
        product_id: str,
        forecasted_demand: float,
        actual_demand: Optional[float] = None,
        forecast_error: Optional[float] = None,
        drift_score: Optional[float] = None,
        adaptation_status: Optional[str] = None,
        timestamp: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Persist a forecast record for a product."""

        normalized_id = self._validate_product_id(product_id)
        if self.get_product(normalized_id) is None:
            raise ValueError(f"Product '{normalized_id}' does not exist.")

        try:
            forecast_value = float(forecasted_demand)
        except (TypeError, ValueError) as exc:
            raise ValueError("forecasted_demand must be numeric.") from exc

        if actual_demand is not None:
            actual_value = float(actual_demand)
        else:
            actual_value = None

        if forecast_error is not None:
            error_value = float(forecast_error)
        else:
            error_value = None

        if drift_score is not None:
            drift_value = float(drift_score)
        else:
            drift_value = None

        ts = self._normalize_timestamp(timestamp)

        cursor = self.connection.execute(
            """
            INSERT INTO forecast_records (
                product_id,
                timestamp,
                forecasted_demand,
                actual_demand,
                forecast_error,
                drift_score,
                adaptation_status
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                normalized_id,
                ts,
                forecast_value,
                actual_value,
                error_value,
                drift_value,
                adaptation_status,
            ),
        )
        self.connection.commit()

        return {
            "id": cursor.lastrowid,
            "product_id": normalized_id,
            "timestamp": ts,
            "forecasted_demand": forecast_value,
            "actual_demand": actual_value,
            "forecast_error": error_value,
            "drift_score": drift_value,
            "adaptation_status": adaptation_status,
        }

    def save_inventory_recommendation(
        self,
        product_id: str,
        safety_stock: float,
        reorder_point: float,
        recommended_reorder_quantity: float,
        stock_out_risk: float,
        excess_inventory_risk: float,
        inventory_status: str,
        timestamp: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Persist the inventory recommendation for a product."""

        normalized_id = self._validate_product_id(product_id)
        if self.get_product(normalized_id) is None:
            raise ValueError(f"Product '{normalized_id}' does not exist.")

        values = [
            ("safety_stock", safety_stock),
            ("reorder_point", reorder_point),
            ("recommended_reorder_quantity", recommended_reorder_quantity),
            ("stock_out_risk", stock_out_risk),
            ("excess_inventory_risk", excess_inventory_risk),
        ]

        for field_name, field_value in values:
            try:
                float(field_value)
            except (TypeError, ValueError) as exc:
                raise ValueError(f"{field_name} must be numeric.") from exc

        if inventory_status is None or str(inventory_status).strip() == "":
            raise ValueError("inventory_status is required.")

        ts = self._normalize_timestamp(timestamp)

        cursor = self.connection.execute(
            """
            INSERT INTO inventory_recommendations (
                product_id,
                timestamp,
                safety_stock,
                reorder_point,
                recommended_reorder_quantity,
                stock_out_risk,
                excess_inventory_risk,
                inventory_status
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                normalized_id,
                ts,
                float(safety_stock),
                float(reorder_point),
                float(recommended_reorder_quantity),
                float(stock_out_risk),
                float(excess_inventory_risk),
                str(inventory_status).strip(),
            ),
        )
        self.connection.commit()

        return {
            "id": cursor.lastrowid,
            "product_id": normalized_id,
            "timestamp": ts,
            "safety_stock": float(safety_stock),
            "reorder_point": float(reorder_point),
            "recommended_reorder_quantity": float(recommended_reorder_quantity),
            "stock_out_risk": float(stock_out_risk),
            "excess_inventory_risk": float(excess_inventory_risk),
            "inventory_status": str(inventory_status).strip(),
        }

    def get_recent_forecasts(
        self,
        product_id: Optional[str] = None,
        limit: int = 10,
    ) -> List[Dict[str, Any]]:
        """Return recent forecast records for one product or all products."""

        if limit <= 0:
            return []

        if product_id is not None:
            normalized_id = self._validate_product_id(product_id)
            rows = self.connection.execute(
                "SELECT * FROM forecast_records WHERE product_id = ? ORDER BY timestamp DESC LIMIT ?",
                (normalized_id, int(limit)),
            ).fetchall()
        else:
            rows = self.connection.execute(
                "SELECT * FROM forecast_records ORDER BY timestamp DESC LIMIT ?",
                (int(limit),),
            ).fetchall()

        return [dict(row) for row in rows]

    def get_recent_demand(
        self,
        product_id: Optional[str] = None,
        limit: int = 10,
    ) -> List[Dict[str, Any]]:
        """Return recent demand records for a product or all products."""

        if limit <= 0:
            return []

        if product_id is not None:
            normalized_id = self._validate_product_id(product_id)
            rows = self.connection.execute(
                "SELECT * FROM demand_history WHERE product_id = ? ORDER BY timestamp DESC LIMIT ?",
                (normalized_id, int(limit)),
            ).fetchall()
        else:
            rows = self.connection.execute(
                "SELECT * FROM demand_history ORDER BY timestamp DESC LIMIT ?",
                (int(limit),),
            ).fetchall()

        return [dict(row) for row in rows]

    def get_adaptation_events(
        self,
        product_id: Optional[str] = None,
        limit: int = 20,
    ) -> List[Dict[str, Any]]:
        """Return stored adaptation events, if any are available."""

        if limit <= 0:
            return []

        if product_id is not None:
            normalized_id = self._validate_product_id(product_id)
            rows = self.connection.execute(
                "SELECT * FROM adaptation_events WHERE product_id = ? ORDER BY timestamp DESC LIMIT ?",
                (normalized_id, int(limit)),
            ).fetchall()
        else:
            rows = self.connection.execute(
                "SELECT * FROM adaptation_events ORDER BY timestamp DESC LIMIT ?",
                (int(limit),),
            ).fetchall()

        return [dict(row) for row in rows]

    def save_adaptation_event(
        self,
        event_type: str,
        details: Optional[str] = None,
        product_id: Optional[str] = None,
        drift_score: Optional[float] = None,
        adaptation_status: Optional[str] = None,
        timestamp: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Persist an adaptation event into the local database."""

        if event_type is None or str(event_type).strip() == "":
            raise ValueError("event_type is required.")

        normalized_product_id = None
        if product_id is not None:
            normalized_product_id = self._validate_product_id(product_id)

        event_time = self._normalize_timestamp(timestamp)

        cursor = self.connection.execute(
            """
            INSERT INTO adaptation_events (
                product_id,
                timestamp,
                event_type,
                details,
                drift_score,
                adaptation_status
            ) VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                normalized_product_id,
                event_time,
                str(event_type).strip(),
                details,
                float(drift_score) if drift_score is not None else None,
                adaptation_status,
            ),
        )
        self.connection.commit()

        return {
            "id": cursor.lastrowid,
            "product_id": normalized_product_id,
            "timestamp": event_time,
            "event_type": str(event_type).strip(),
            "details": details,
            "drift_score": float(drift_score) if drift_score is not None else None,
            "adaptation_status": adaptation_status,
        }

    def close(self) -> None:
        """Close the SQLite connection if it is open."""

        if self._connection is not None:
            self._connection.close()
            self._connection = None


__all__ = ["RetailDatabase"]
